FirewallDnsName = "pan-fw"
FirewallVmName = "PANW"
FirewallVmSize = "Standard_D3_v2"
FromGatewayLogin = "0.0.0.0/0"
StorageAccountName = "stg20"
WebServerDnsName = "pan-web"
location = "centralus"
resource_group_name = "demo-rg20"
